<?php

use Migrations\AbstractMigration;

class ApplicationSettings extends AbstractMigration
{

    public function up()
    {

        $this->table('settings')
            ->addColumn('created', 'datetime', [
                'default' => null,
                'limit' => null,
                'null' => true,
            ])
            ->addColumn('modified', 'datetime', [
                'default' => null,
                'limit' => null,
                'null' => true,
            ])
            ->addColumn('name', 'string', [
                'default' => null,
                'limit' => 50,
                'null' => true,
            ])
            ->addColumn('description', 'string', [
                'default' => null,
                'limit' => 1024,
                'null' => true,
            ])
            ->addColumn('property_group', 'string', [
                'default' => null,
                'limit' => 50,
                'null' => true,
            ])
            ->addColumn('property_key', 'string', [
                'default' => null,
                'limit' => 50,
                'null' => true,
            ])
            ->addColumn('property_value', 'string', [
                'default' => null,
                'limit' => 1024,
                'null' => true,
            ])
            ->addColumn('selections', 'text', [
                'default' => null,
                'limit' => null,
                'null' => true,
            ])
            ->addColumn('html_select_type', 'string', [
                'default' => null,
                'limit' => 50,
                'null' => true,
            ])
            ->addColumn('match_pattern', 'string', [
                'default' => null,
                'limit' => 50,
                'null' => true,
            ])
            ->addColumn('is_masked', 'boolean', [
                'default' => false,
                'limit' => null,
                'null' => true,
            ])
            ->create();

        $this->seedSettings();
    }

    public function down()
    {
        $this->dropTable('settings');
    }

    public function seedSettings()
    {
        $currentDate = gmdate("Y-m-d H:i:s");

        $data = [
            [
                'created' => $currentDate,
                'modified' => $currentDate,
                'name' => 'Date Format',
                'description' => 'Format of the Date as presented in the GUI',
                'property_group' => 'locale',
                'property_key' => 'date_format',
                'property_value' => 'yyyy-MM-dd',
                'selections' => '{
"Year-Month-Day": {
"yyyy-MM-dd": "yyyy-mm-dd"
},
"Day-Month-Year": {
"dd\/MM\/yyyy": "dd\/mm\/yyyy",
"d\/M\/yy": "d\/m\/yy"
},
"Month-Day-Year": {
"MM\/dd\/yyyy": "mm\/dd\/yyyy",
"M\/d\/yy": "m\/d\/yy"
}
}',
                'html_select_type' => 'select',
                'match_pattern' => null,
                'is_masked' => false
            ],
            [
                'created' => $currentDate,
                'modified' => $currentDate,
                'name' => 'Time Format',
                'description' => 'Format of the Time as presented in the GUI',
                'property_group' => 'locale',
                'property_key' => 'time_format',
                'property_value' => 'HH:mm:ss',
                'selections' => '{
"24-Hour": {
"HH:mm:ss": "hh:mm:ss",
"H:m": "h:m"
},
"12-Hour": {
"hh:mm:ss a": "hh:mm:ss am\/pm",
"h:m a": "h:m am\/pm"
}
}',
                'html_select_type' => 'select',
                'match_pattern' => null,
                'is_masked' => false
            ],
            [
                'created' => $currentDate,
                'modified' => $currentDate,
                'name' => 'Date and Time Format',
                'description' => 'Format of the Date and Time as presented in the GUI',
                'property_group' => 'locale',
                'property_key' => 'datetime_format',
                'property_value' => 'yyyy-MM-dd HH:mm:ss',
                'selections' => '{
"yyyy-MM-dd HH:mm:ss": "yyyy-mm-dd hh:mm:ss",
"0": "Tuesday, April 12, 1952 AD or 3:30:42pm PST",
"1": "January 12, 1952 or 3:30:32pm",
"2": "Jan 12, 1952",
"3": "12\/13\/52 or 3:30pm"
}',
                'html_select_type' => 'select',
                'match_pattern' => null,
                'is_masked' => false
            ],
            [
                'created' => $currentDate,
                'modified' => $currentDate,
                'name' => 'Weeks Starts On',
                'description' => 'The first day of the week',
                'property_group' => 'locale',
                'property_key' => 'week_start',
                'property_value' => 'Sunday',
                'selections' => '{"Sunday":"Sunday","Monday":"Monday","Tuesday":"Tuesday","Wednesday":"Wednesday","Thursday":"Thursday","Friday":"Friday","Saturday":"Saturday"}',
                'html_select_type' => 'select',
                'match_pattern' => null,
                'is_masked' => false
            ],
            [
                'created' => $currentDate,
                'modified' => $currentDate,
                'name' => 'Timezone',
                'description' => 'Timezone of the Application',
                'property_group' => 'locale',
                'property_key' => 'timezone',
                'property_value' => 'Australia/Sydney',
                'selections' => '{
"Africa": {
"Africa\/Abidjan": "Abidjan",
"Africa\/Accra": "Accra",
"Africa\/Addis_Ababa": "Addis Ababa",
"Africa\/Algiers": "Algiers",
"Africa\/Asmara": "Asmara",
"Africa\/Bamako": "Bamako",
"Africa\/Bangui": "Bangui",
"Africa\/Banjul": "Banjul",
"Africa\/Bissau": "Bissau",
"Africa\/Blantyre": "Blantyre",
"Africa\/Brazzaville": "Brazzaville",
"Africa\/Bujumbura": "Bujumbura",
"Africa\/Cairo": "Cairo",
"Africa\/Casablanca": "Casablanca",
"Africa\/Ceuta": "Ceuta",
"Africa\/Conakry": "Conakry",
"Africa\/Dakar": "Dakar",
"Africa\/Dar_es_Salaam": "Dar es Salaam",
"Africa\/Djibouti": "Djibouti",
"Africa\/Douala": "Douala",
"Africa\/El_Aaiun": "El Aaiun",
"Africa\/Freetown": "Freetown",
"Africa\/Gaborone": "Gaborone",
"Africa\/Harare": "Harare",
"Africa\/Johannesburg": "Johannesburg",
"Africa\/Juba": "Juba",
"Africa\/Kampala": "Kampala",
"Africa\/Khartoum": "Khartoum",
"Africa\/Kigali": "Kigali",
"Africa\/Kinshasa": "Kinshasa",
"Africa\/Las": "Las",
"Africa\/Libreville": "Libreville",
"Africa\/Lome": "Lome",
"Africa\/Luanda": "Luanda",
"Africa\/Lubumbashi": "Lubumbashi",
"Africa\/Lusaka": "Lusaka",
"Africa\/Malabo": "Malabo",
"Africa\/Maputo": "Maputo",
"Africa\/Maseru": "Maseru",
"Africa\/Mbabane": "Mbabane",
"Africa\/Mogadishu": "Mogadishu",
"Africa\/Monrovia": "Monrovia",
"Africa\/Nairobi": "Nairobi",
"Africa\/Ndjamena": "Ndjamena",
"Africa\/Niamey": "Niamey",
"Africa\/Nouakchott": "Nouakchott",
"Africa\/Ouagadouu": "Ouagadouu",
"Africa\/Porto-Novo": "Porto-Novo",
"Africa\/Sao_Tome": "Sao Tome",
"Africa\/Tripoli": "Tripoli",
"Africa\/Tunis": "Tunis",
"Africa\/Windhoek": "Windhoek"
},
"America": {
"America\/Adak": "Adak",
"America\/Anchorage": "Anchorage",
"America\/Anguilla": "Anguilla",
"America\/Antigua": "Antigua",
"America\/Araguaina": "Araguaina",
"America\/Argentina": "Argentina",
"America\/Aruba": "Aruba",
"America\/Asuncion": "Asuncion",
"America\/Atikokan": "Atikokan",
"America\/Bahia": "Bahia",
"America\/Bahia_Banderas": "Bahia Banderas",
"America\/Barbados": "Barbados",
"America\/Belem": "Belem",
"America\/Belize": "Belize",
"America\/Blanc-Sablon": "Blanc-Sablon",
"America\/Boa_Vista": "Boa Vista",
"America\/Bota": "Bota",
"America\/Boise": "Boise",
"America\/Cambridge_Bay": "Cambridge Bay",
"America\/Campo_Grande": "Campo Grande",
"America\/Cancun": "Cancun",
"America\/Caracas": "Caracas",
"America\/Cayenne": "Cayenne",
"America\/Cayman": "Cayman",
"America\/Chica": "Chica",
"America\/Chihuahua": "Chihuahua",
"America\/Costa_Rica": "Costa Rica",
"America\/Creston": "Creston",
"America\/Cuiaba": "Cuiaba",
"America\/Curacao": "Curacao",
"America\/Danmarkshavn": "Danmarkshavn",
"America\/Dawson": "Dawson",
"America\/Dawson_Creek": "Dawson Creek",
"America\/Denver": "Denver",
"America\/Detroit": "Detroit",
"America\/Dominica": "Dominica",
"America\/Edmonton": "Edmonton",
"America\/Eirunepe": "Eirunepe",
"America\/El_Salvador": "El Salvador",
"America\/Fort_Nelson": "Fort Nelson",
"America\/Fortaleza": "Fortaleza",
"America\/Glace_Bay": "Glace Bay",
"America\/dthab": "dthab",
"America\/ose_Bay": "ose Bay",
"America\/Grand_Turk": "Grand Turk",
"America\/Grenada": "Grenada",
"America\/Guadeloupe": "Guadeloupe",
"America\/Guatemala": "Guatemala",
"America\/Guayaquil": "Guayaquil",
"America\/Guyana": "Guyana",
"America\/Halifax": "Halifax",
"America\/Havana": "Havana",
"America\/Hermosillo": "Hermosillo",
"America\/Indiana": "Indiana",
"America\/Inuvik": "Inuvik",
"America\/Iqaluit": "Iqaluit",
"America\/Jamaica": "Jamaica",
"America\/Juneau": "Juneau",
"America\/Kentucky": "Kentucky",
"America\/Kralendijk": "Kralendijk",
"America\/La_Paz": "La Paz",
"America\/Lima": "Lima",
"America\/Los_Angeles": "Los Angeles",
"America\/Lower_Princes": "Lower Princes",
"America\/Maceio": "Maceio",
"America\/Managua": "Managua",
"America\/Manaus": "Manaus",
"America\/Marit": "Marit",
"America\/Martinique": "Martinique",
"America\/Matamoros": "Matamoros",
"America\/Mazatlan": "Mazatlan",
"America\/Menominee": "Menominee",
"America\/Merida": "Merida",
"America\/Metlakatla": "Metlakatla",
"America\/Mexico_City": "Mexico City",
"America\/Miquelon": "Miquelon",
"America\/Moncton": "Moncton",
"America\/Monterrey": "Monterrey",
"America\/Montevideo": "Montevideo",
"America\/Montserrat": "Montserrat",
"America\/Nassau": "Nassau",
"America\/New_York": "New York",
"America\/Nipin": "Nipin",
"America\/Nome": "Nome",
"America\/Noronha": "Noronha",
"America\/North_Dakota": "North Dakota",
"America\/Ojinaga": "Ojinaga",
"America\/Panama": "Panama",
"America\/Pangnirtung": "Pangnirtung",
"America\/Paramaribo": "Paramaribo",
"America\/Phoenix": "Phoenix",
"America\/Port-au-Prince": "Port-au-Prince",
"America\/Port_of_Spain": "Port of Spain",
"America\/Porto_Velho": "Porto Velho",
"America\/Puerto_Rico": "Puerto Rico",
"America\/Rainy_River": "Rainy River",
"America\/Rankin_Inlet": "Rankin Inlet",
"America\/Recife": "Recife",
"America\/Regina": "Regina",
"America\/Resolute": "Resolute",
"America\/Rio_Branco": "Rio Branco",
"America\/Santa_Isabel": "Santa Isabel",
"America\/Santarem": "Santarem",
"America\/Santia": "Santia",
"America\/Santo_Domin": "Santo Domin",
"America\/Sao_Paulo": "Sao Paulo",
"America\/Scoresbysund": "Scoresbysund",
"America\/Sitka": "Sitka",
"America\/St_Barthelemy": "St Barthelemy",
"America\/St_Johns": "St Johns",
"America\/St_Kitts": "St Kitts",
"America\/St_Lucia": "St Lucia",
"America\/St_Thomas": "St Thomas",
"America\/St_Vincent": "St Vincent",
"America\/Swift_Current": "Swift Current",
"America\/Tegucigalpa": "Tegucigalpa",
"America\/Thule": "Thule",
"America\/Thunder_Bay": "Thunder Bay",
"America\/Tijuana": "Tijuana",
"America\/Toronto": "Toronto",
"America\/Tortola": "Tortola",
"America\/Vancouver": "Vancouver",
"America\/Whitehorse": "Whitehorse",
"America\/Winnipeg": "Winnipeg",
"America\/Yakutat": "Yakutat",
"America\/Yellowknife": "Yellowknife"
},
"Antarctica": {
"Antarctica\/Casey": "Casey",
"Antarctica\/Davis": "Davis",
"Antarctica\/DumontDUrville": "DumontDUrville",
"Antarctica\/Macquarie": "Macquarie",
"Antarctica\/Mawson": "Mawson",
"Antarctica\/McMurdo": "McMurdo",
"Antarctica\/Palmer": "Palmer",
"Antarctica\/Rothera": "Rothera",
"Antarctica\/Syowa": "Syowa",
"Antarctica\/Troll": "Troll",
"Antarctica\/Vostok": "Vostok"
},
"Arctic": {
"Arctic\/Longyearbyen": "Longyearbyen"
},
"Asia": {
"Asia\/Aden": "Aden",
"Asia\/Almaty": "Almaty",
"Asia\/Amman": "Amman",
"Asia\/Anadyr": "Anadyr",
"Asia\/Aqtau": "Aqtau",
"Asia\/Aqtobe": "Aqtobe",
"Asia\/Ashgabat": "Ashgabat",
"Asia\/Baghdad": "Baghdad",
"Asia\/Bahrain": "Bahrain",
"Asia\/Baku": "Baku",
"Asia\/Bangkok": "Bangkok",
"Asia\/Beirut": "Beirut",
"Asia\/Bishkek": "Bishkek",
"Asia\/Brunei": "Brunei",
"Asia\/Chita": "Chita",
"Asia\/Choibalsan": "Choibalsan",
"Asia\/Colombo": "Colombo",
"Asia\/Damascus": "Damascus",
"Asia\/Dhaka": "Dhaka",
"Asia\/Dili": "Dili",
"Asia\/Dubai": "Dubai",
"Asia\/Dushanbe": "Dushanbe",
"Asia\/Gaza": "Gaza",
"Asia\/Hebron": "Hebron",
"Asia\/Ho_Chi_Minh": "Ho Chi Minh",
"Asia\/Hong_Kong": "Hong Kong",
"Asia\/Hovd": "Hovd",
"Asia\/Irkutsk": "Irkutsk",
"Asia\/Jakarta": "Jakarta",
"Asia\/Jayapura": "Jayapura",
"Asia\/Jerusalem": "Jerusalem",
"Asia\/Kabul": "Kabul",
"Asia\/Kamchatka": "Kamchatka",
"Asia\/Karachi": "Karachi",
"Asia\/Kathmandu": "Kathmandu",
"Asia\/Khandyga": "Khandyga",
"Asia\/Kolkata": "Kolkata",
"Asia\/Krasnoyarsk": "Krasnoyarsk",
"Asia\/Kuala_Lumpur": "Kuala Lumpur",
"Asia\/Kuching": "Kuching",
"Asia\/Kuwait": "Kuwait",
"Asia\/Macau": "Macau",
"Asia\/Magadan": "Magadan",
"Asia\/Makassar": "Makassar",
"Asia\/Manila": "Manila",
"Asia\/Muscat": "Muscat",
"Asia\/Nicosia": "Nicosia",
"Asia\/Novokuznetsk": "Novokuznetsk",
"Asia\/Novosibirsk": "Novosibirsk",
"Asia\/Omsk": "Omsk",
"Asia\/Oral": "Oral",
"Asia\/Phnom_Penh": "Phnom Penh",
"Asia\/Pontianak": "Pontianak",
"Asia\/Pyongyang": "Pyongyang",
"Asia\/Qatar": "Qatar",
"Asia\/Qyzylorda": "Qyzylorda",
"Asia\/Ranon": "Ranon",
"Asia\/Riyadh": "Riyadh",
"Asia\/Sakhalin": "Sakhalin",
"Asia\/Samarkand": "Samarkand",
"Asia\/Seoul": "Seoul",
"Asia\/Shanghai": "Shanghai",
"Asia\/Singapore": "Singapore",
"Asia\/Srednekolymsk": "Srednekolymsk",
"Asia\/Taipei": "Taipei",
"Asia\/Tashkent": "Tashkent",
"Asia\/Tbilisi": "Tbilisi",
"Asia\/Tehran": "Tehran",
"Asia\/Thimphu": "Thimphu",
"Asia\/Tokyo": "Tokyo",
"Asia\/Ulaanbaatar": "Ulaanbaatar",
"Asia\/Urumqi": "Urumqi",
"Asia\/Ust-Nera": "Ust-Nera",
"Asia\/Vientiane": "Vientiane",
"Asia\/Vladivostok": "Vladivostok",
"Asia\/Yakutsk": "Yakutsk",
"Asia\/Yekaterinburg": "Yekaterinburg",
"Asia\/Yerevan": "Yerevan"
},
"Atlantic": {
"Atlantic\/Azores": "Azores",
"Atlantic\/Bermuda": "Bermuda",
"Atlantic\/Canary": "Canary",
"Atlantic\/Cape_Verde": "Cape Verde",
"Atlantic\/Faroe": "Faroe",
"Atlantic\/Madeira": "Madeira",
"Atlantic\/Reykjavik": "Reykjavik",
"Atlantic\/South_Georgia": "South Georgia",
"Atlantic\/St_Helena": "St Helena",
"Atlantic\/Stanley": "Stanley"
},
"Australia": {
"Australia\/Adelaide": "Adelaide",
"Australia\/Brisbane": "Brisbane",
"Australia\/Broken_Hill": "Broken Hill",
"Australia\/Currie": "Currie",
"Australia\/Darwin": "Darwin",
"Australia\/Eucla": "Eucla",
"Australia\/Hobart": "Hobart",
"Australia\/Lindeman": "Lindeman",
"Australia\/Lord_Howe": "Lord Howe",
"Australia\/Melbourne": "Melbourne",
"Australia\/Perth": "Perth",
"Australia\/Sydney": "Sydney"
},
"Europe": {
"Europe\/Amsterdam": "Amsterdam",
"Europe\/Andorra": "Andorra",
"Europe\/Athens": "Athens",
"Europe\/Belgrade": "Belgrade",
"Europe\/Berlin": "Berlin",
"Europe\/Bratislava": "Bratislava",
"Europe\/Brussels": "Brussels",
"Europe\/Bucharest": "Bucharest",
"Europe\/Budapest": "Budapest",
"Europe\/Busingen": "Busingen",
"Europe\/Chisinau": "Chisinau",
"Europe\/Copenhagen": "Copenhagen",
"Europe\/Dublin": "Dublin",
"Europe\/Gibraltar": "Gibraltar",
"Europe\/Guernsey": "Guernsey",
"Europe\/Helsinki": "Helsinki",
"Europe\/Isle_of_Man": "Isle of Man",
"Europe\/Istanbul": "Istanbul",
"Europe\/Jersey": "Jersey",
"Europe\/Kaliningrad": "Kaliningrad",
"Europe\/Kiev": "Kiev",
"Europe\/Lisbon": "Lisbon",
"Europe\/Ljubljana": "Ljubljana",
"Europe\/London": "London",
"Europe\/Luxembourg": "Luxembourg",
"Europe\/Madrid": "Madrid",
"Europe\/Malta": "Malta",
"Europe\/Mariehamn": "Mariehamn",
"Europe\/Minsk": "Minsk",
"Europe\/Monaco": "Monaco",
"Europe\/Moscow": "Moscow",
"Europe\/Oslo": "Oslo",
"Europe\/Paris": "Paris",
"Europe\/Podrica": "Podrica",
"Europe\/Prague": "Prague",
"Europe\/Riga": "Riga",
"Europe\/Rome": "Rome",
"Europe\/Samara": "Samara",
"Europe\/San_Marino": "San Marino",
"Europe\/Sarajevo": "Sarajevo",
"Europe\/Simferopol": "Simferopol",
"Europe\/Skopje": "Skopje",
"Europe\/Sofia": "Sofia",
"Europe\/Stockholm": "Stockholm",
"Europe\/Tallinn": "Tallinn",
"Europe\/Tirane": "Tirane",
"Europe\/Uzhrod": "Uzhrod",
"Europe\/Vaduz": "Vaduz",
"Europe\/Vatican": "Vatican",
"Europe\/Vienna": "Vienna",
"Europe\/Vilnius": "Vilnius",
"Europe\/Volgrad": "Volgrad",
"Europe\/Warsaw": "Warsaw",
"Europe\/Zagreb": "Zagreb",
"Europe\/Zaporozhye": "Zaporozhye",
"Europe\/Zurich": "Zurich"
},
"Indian": {
"Indian\/Antananarivo": "Antananarivo",
"Indian\/Chas": "Chas",
"Indian\/Christmas": "Christmas",
"Indian\/Cocos": "Cocos",
"Indian\/Comoro": "Comoro",
"Indian\/Kerguelen": "Kerguelen",
"Indian\/Mahe": "Mahe",
"Indian\/Maldives": "Maldives",
"Indian\/Mauritius": "Mauritius",
"Indian\/Mayotte": "Mayotte",
"Indian\/Reunion": "Reunion"
},
"Pacific": {
"Pacific\/Apia": "Apia",
"Pacific\/Auckland": "Auckland",
"Pacific\/Bougainville": "Bougainville",
"Pacific\/Chatham": "Chatham",
"Pacific\/Chuuk": "Chuuk",
"Pacific\/Easter": "Easter",
"Pacific\/Efate": "Efate",
"Pacific\/Enderbury": "Enderbury",
"Pacific\/Fakaofo": "Fakaofo",
"Pacific\/Fiji": "Fiji",
"Pacific\/Funafuti": "Funafuti",
"Pacific\/Galapas": "Galapas",
"Pacific\/Gambier": "Gambier",
"Pacific\/Guadalcanal": "Guadalcanal",
"Pacific\/Guam": "Guam",
"Pacific\/Honolulu": "Honolulu",
"Pacific\/Johnston": "Johnston",
"Pacific\/Kiritimati": "Kiritimati",
"Pacific\/Kosrae": "Kosrae",
"Pacific\/Kwajalein": "Kwajalein",
"Pacific\/Majuro": "Majuro",
"Pacific\/Marquesas": "Marquesas",
"Pacific\/Midway": "Midway",
"Pacific\/Nauru": "Nauru",
"Pacific\/Niue": "Niue",
"Pacific\/Norfolk": "Norfolk",
"Pacific\/Noumea": "Noumea",
"Pacific\/Pa_Pa": "Pa Pa",
"Pacific\/Palau": "Palau",
"Pacific\/Pitcairn": "Pitcairn",
"Pacific\/Pohnpei": "Pohnpei",
"Pacific\/Port_Moresby": "Port Moresby",
"Pacific\/Rarotonga": "Rarotonga",
"Pacific\/Saipan": "Saipan",
"Pacific\/Tahiti": "Tahiti",
"Pacific\/Tarawa": "Tarawa",
"Pacific\/Tongatapu": "Tongatapu",
"Pacific\/Wake": "Wake",
"Pacific\/Wallis": "Wallis"
}
}',
                'html_select_type' => 'select',
                'match_pattern' => null,
                'is_masked' => false
            ],
            [
                'created' => $currentDate,
                'modified' => $currentDate,
                'name' => 'URL Base Path',
                'description' => 'Base URL where the reports can be retrieved from',
                'property_group' => 'server',
                'property_key' => 'base_url',
                'property_value' => 'http://' . gethostname() . '/',
                'selections' => null,
                'html_select_type' => 'text',
                'match_pattern' => null,
                'is_masked' => false
            ],
            [
                'created' => $currentDate,
                'modified' => $currentDate,
                'name' => 'UNC Base Path',
                'description' => 'Base UNC where the reports can be retrieved from',
                'property_group' => 'server',
                'property_key' => 'base_unc',
                'property_value' => '\\\\' . gethostname() . '\\Share_Storage\\',
                'selections' => null,
                'html_select_type' => 'text',
                'match_pattern' => null,
                'is_masked' => false
            ],
            [
                'created' => $currentDate,
                'modified' => $currentDate,
                'name' => 'Hot Folder UNC Path',
                'description' => 'Location of the WaSP Hot Folders',
                'property_group' => 'server',
                'property_key' => 'hot_folder_unc',
                'property_value' => '\\\\' . gethostname() . '\\Share_HotFolders\\',
                'selections' => null,
                'html_select_type' => 'text',
                'match_pattern' => null,
                'is_masked' => false
            ],
            [
                'created' => $currentDate,
                'modified' => $currentDate,
                'name' => 'UNC Base Path',
                'description' => 'Location of the WaSP Temporary Folder',
                'property_group' => 'server',
                'property_key' => 'tmp_folder_unc',
                'property_value' => '\\\\' . gethostname() . '\\Share_Tmp\\',
                'selections' => null,
                'html_select_type' => 'text',
                'match_pattern' => null,
                'is_masked' => false
            ],
            [
                'created' => $currentDate,
                'modified' => $currentDate,
                'name' => 'Email SMTP Server',
                'description' => 'The SMTP server used to send emails',
                'property_group' => 'email_server',
                'property_key' => 'email_smtp_host',
                'property_value' => '127.0.0.1',
                'selections' => '',
                'html_select_type' => 'text',
                'match_pattern' => null,
                'is_masked' => '0',
            ],
            [
                'created' => $currentDate,
                'modified' => $currentDate,
                'name' => 'Email SMTP Server Port',
                'description' => 'The Port to use on the SMTP server',
                'property_group' => 'email_server',
                'property_key' => 'email_smtp_port',
                'property_value' => '25',
                'selections' => '',
                'html_select_type' => 'text',
                'match_pattern' => null,
                'is_masked' => '0',
            ],
            [
                'created' => $currentDate,
                'modified' => $currentDate,
                'name' => 'Email TLS',
                'description' => 'Use TLS Security when sending emails',
                'property_group' => 'email_server',
                'property_key' => 'email_tls',
                'property_value' => 'false',
                'selections' => '{"false":"False","true":"True"}',
                'html_select_type' => 'select',
                'match_pattern' => null,
                'is_masked' => '0',
            ],
            [
                'created' => $currentDate,
                'modified' => $currentDate,
                'name' => 'Email Username',
                'description' => 'If the SMTP server requires a username and password',
                'property_group' => 'email_server',
                'property_key' => 'email_username',
                'property_value' => '',
                'selections' => '',
                'html_select_type' => 'text',
                'match_pattern' => null,
                'is_masked' => '0',
            ],
            [
                'created' => $currentDate,
                'modified' => $currentDate,
                'name' => 'Email Password',
                'description' => 'If the SMTP server requires a username and password',
                'property_group' => 'email_server',
                'property_key' => 'email_password',
                'property_value' => '',
                'selections' => '',
                'html_select_type' => 'text',
                'match_pattern' => null,
                'is_masked' => '1',
            ],
            [
                'created' => $currentDate,
                'modified' => $currentDate,
                'name' => 'Email From Name',
                'description' => 'The Application will use this name when sending emails',
                'property_group' => 'email_server',
                'property_key' => 'email_from_name',
                'property_value' => 'Application Stub',
                'selections' => '',
                'html_select_type' => 'text',
                'match_pattern' => null,
                'is_masked' => '0',
            ],
            [
                'created' => $currentDate,
                'modified' => $currentDate,
                'name' => 'Email From Address',
                'description' => 'The Application will use this email when sending emails',
                'property_group' => 'email_server',
                'property_key' => 'email_from_address',
                'property_value' => 'app@localhost.com',
                'selections' => '',
                'html_select_type' => 'text',
                'match_pattern' => null,
                'is_masked' => '0',
            ],
            [
                'created' => $currentDate,
                'modified' => $currentDate,
                'name' => 'Email From Address',
                'description' => 'The default TO when sending emails',
                'property_group' => 'email_server',
                'property_key' => 'email_to_address',
                'property_value' => 'to@example.com',
                'selections' => '',
                'html_select_type' => 'text',
                'match_pattern' => null,
                'is_masked' => '0',
            ],
            [
                'created' => $currentDate,
                'modified' => $currentDate,
                'name' => 'Email From Address',
                'description' => 'The default CC when sending emails',
                'property_group' => 'email_server',
                'property_key' => 'email_cc_address',
                'property_value' => 'cc@example.com',
                'selections' => '',
                'html_select_type' => 'text',
                'match_pattern' => null,
                'is_masked' => '0',
            ],
            [
                'created' => $currentDate,
                'modified' => $currentDate,
                'name' => 'Email From Address',
                'description' => 'The default BCC when sending emails',
                'property_group' => 'email_server',
                'property_key' => 'email_bcc_address',
                'property_value' => 'bcc@example.com',
                'selections' => '',
                'html_select_type' => 'text',
                'match_pattern' => null,
                'is_masked' => '0',
            ],
        ];

        if (!empty($data)) {
            $table = $this->table('settings');
            $table->insert($data)->save();
        }
    }

}

